валидация и требования
Prostoe-menu/prostoemenu_dev pull request #101
Opened 2023-10-16 17:58 UTC by psevdo212

Сделана валидация и под требования тоже подогнал.
Исключение: звездочки сложности. В требованиях написано что у них должны красными становиться края, но компонент у меня от MUI и наши кастомные звездочки туда не очень лезут (размеры у них разные походу у пустых и заполненных), так что я только сделал подпись "Это поле надо заполнить" вместо красных границ.
Прошу обратить внимание на поле с количеством порций - у меня ощущение что я там перемудрил с установкой значений для Hook Form, но может это и не так.
Так же есть затык небольшой при валидации поля с обрезкой фотки:
при первой валидации если там ничего нет - границы поля подсвечиваются, а после добавления фото и его удаления - при нажатии кнопки "Отправить" тост с требованием заполнить поля появляется,  а вот границы не краснеют....
Не могу понять в какую. сторону копать пока.

2023-10-16 20:13 UTC, lipnitskaite requested changes
привет!
на что обратила внимание:
1. в консоли есть ворнинги
2. удалить закомментированный код, его много, не стала повторяться. возможно, когда код станет почище, увижу еще что-то
4. компонент MainInfo получился ну очень большим, почти 450 строк кода для одного компонента - это слишком тяжело для восприятия. При этом у тебя там много повторяющихся компонентов (подзаголовки, инпуты, кнопки), подумай, пожалуйста, как его можно порефакторить, если будет возможность.

2023-10-16 20:13 UTC, lipnitskaite commented on front/src/components/UI/PhotoButton/PhotoButton.jsx
> +const PhotoButton = (error) => {
```suggestion
const PhotoButton = ({ error }) => {
```

это исправит ошибку с тем, что кнопка красная при открытии страницы

2023-10-16 20:13 UTC, lipnitskaite commented on front/src/components/UI/PhotoButton/PhotoButton.jsx
>              checkOrientation={false} // https://github.com/fengyuanchen/cropperjs/issues/671
если комментарий с отсылкой на issue несет ценность, то распиши подробно, в чем

2023-10-17 14:09 UTC, psevdo212 commented on front/src/components/UI/PhotoButton/PhotoButton.jsx
>              checkOrientation={false} // https://github.com/fengyuanchen/cropperjs/issues/671
этот компонент писал не я, так что видимо этот коммент висит там непосредственно от разраба DropZone. Убрал его, потому что нет смысла в нем.

2023-10-17 14:34 UTC, psevdo212 commented on front/src/components/AddRecipeForm/MainInfo/MainInfo.jsx
>          {errors?.recipeName?.type === 'minLength' && (
в тех требованиях, что мне Катя скинула - при ошибках паттерна или минимальном количестве букв - идет и тост и подпись под полем

2023-10-17 14:36 UTC, psevdo212 commented on front/src/components/AddRecipeForm/MainInfo/MainInfo.jsx
>    function nameChange(event) {
согласен

2023-10-17 14:38 UTC, psevdo212 commented on front/src/components/AddRecipeForm/MainInfo/MainInfo.jsx
> +        {/* {errors?.recipeName?.type === 'required' && (
поудалял все. Опять забыл перед ПР комменты почистить, каюсь

2023-10-17 14:39 UTC, psevdo212 commented on front/src/components/AddRecipeForm/MainInfo/mainInfo.module.scss
> +    // -moz-appearance: textfield; // в яндекс браузере ломает валидацию
в целом да, можно и удалить наверное. Если в мозилле сломается - уже думать по ходу пьесы

2023-10-17 14:41 UTC, psevdo212 commented on front/src/components/AddRecipeForm/MainInfo/MainInfo.jsx
>                <input
хорошо, я посмотрю, может действительно получится использовать

2023-10-17 14:51 UTC, psevdo212 commented on front/src/components/AddRecipeForm/MainInfo/MainInfo.jsx
> +                value: /^[a-zA-Zа-яА-ЯёЁ0-9\s!%№()\-[\];':"\\|,. /?]+$/i,
да, не подумал - я ж его два раза использую

2023-10-18 08:44 UTC, lipnitskaite requested changes

2023-10-18 08:44 UTC, lipnitskaite commented on front/src/components/AddRecipeForm/MainInfo/MainInfo.jsx
> +    if (getValues('rating') === undefined || 0) {
можно и правда сократить код, как предлагали ребята в чате

2023-10-18 08:44 UTC, lipnitskaite commented on front/src/components/UI/PhotoButton/PhotoButton.jsx
>        console.log(file[0].errors[0]);
не забудь потом убрать все выводы в консоль, когда будешь рефакторить

2023-10-18 08:44 UTC, lipnitskaite commented on front/src/components/UI/PhotoButton/PhotoButton.jsx
>    const thumbs = sourcePhoto?.map((file) => (
здесь было бы здорово либо оставить короткий коммент с описанием, либо сделать более понятное название, так как сторонний человек не поймет, что такое thumbs по коду

2023-10-18 08:44 UTC, lipnitskaite commented on front/src/components/UI/PhotoButton/PhotoButton.jsx
>            alt="preview"
alt пишем на русском, так как у нас русскоязычное приложение

2023-10-18 08:44 UTC, lipnitskaite commented on front/src/components/AddRecipeForm/MainInfo/mainInfo.module.scss
> +    // -moz-appearance: textfield; // в яндекс браузере ломает валидацию
либо сразу посмотреть решение, как этого не допустить)

2023-10-18 08:44 UTC, lipnitskaite commented on front/src/components/AddRecipeForm/MainInfo/MainInfo.jsx
>          {errors?.recipeName?.type === 'minLength' && (
сейчас просто если сразу нажать на "далее", без заполнения полей, выглядит немного странно - где-то тост, где-то ошибка внизу, какие-то инпуты подсвечиваются красным, какие-то - нет.
кстати, увидела еще один важный момент: нет звездочек на обязательных полях, поэтому неочевидно, что нужно заполнять - поставлю коммент

2023-10-18 08:44 UTC, lipnitskaite commented on front/src/components/AddRecipeForm/MainInfo/MainInfo.jsx
> +      <h3 className={styles.title}>Название рецепта</h3>
важно: расхождение с макетом (даже с неактуальной версией)
нет фразы "Поля, отмеченные *, обязательны для заполнения" и нет звездочек у обязательных полей, а это обязательно должно быть

2025-01-19 20:00 UTC, closed without merging