FRONTEND - #119 - сверстаны карточки рецепта
Prostoe-menu/prostoemenu_dev pull request #120
Opened 2023-11-11 15:20 UTC by MZ-87

- сверстала карточки рецепта с моковыми данными и  контейнер каталога
- исправила путь к странице каталога в компоненте App.jsx

2023-11-11 17:28 UTC, 4uku commented on front/.eslintrc.json
> +  "root":false
не хватает пробела после двоеточия

2023-11-16 10:32 UTC, MZ-87 commented on front/.eslintrc.json
> +  "root":false
Вынеси это, пожалуйста, в отдельный ишью, и распиши подробнее, что ещё надо сделать с этим json

2023-11-16 10:55 UTC, 4uku commented on front/.eslintrc.json
> +  "root":false
для отдельного ишью это слишком маленькая задача :) просто отформатируй json в каком-нибудь https://jsonformatter.org/ . Слева вставляешь свой json, справа получаешь отформатированный.

2023-11-16 18:38 UTC, MZ-87 commented on front/.eslintrc.json
> +  "root":false
.eslintrc.json отформатирован

2023-11-17 12:11 UTC, azozulya approved these changes

2023-11-17 14:30 UTC, lipnitskaite requested changes

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      // src="{recipe.image}"
неактуальный закомментированный код удаляем

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/PageTitle/PageTitle.jsx
> +import styles from './pageTitle.module.scss';
название файла для стилей также с большой буквы, как и название компонента

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      // alt="{recipe.name}"
```suggestion
```

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      {/* <h3 className={styles.cardName}>{recipe.name}</h3> */}
```suggestion
```

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      alt="блюдо"
на заметку: подумать, можно ли после получения данных от бэка сделать 'alt' более информативным

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      <div className={styles.cardDescription__item}>
не очень информативное название класса, если это контейнер, то лучше переименовать

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +        {/* здесь должен быть скрипт, добавляющий нужное количество звезд */}
если это что-то, нуждающееся в доработке, то создать issue и вставить сюда ссылку как TO DO
если комментарий не актуален, то удалить

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +        {/* <p className={styles.cardDescription__text}>{recipe.cookhours} час {recipe.cookminutes} мин.</p> */}
```suggestion
```

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.module.scss
> +h3,
ссылаемся на классы, а не на теги

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeGallery.jsx
> +      <div>
точно ли нам нужен этот промежуточный div?

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeGallery.jsx
> +                /* eslint-disable-next-line react/no-array-index-key */
не мьютим правило, в key лучше не задавать index, а задавать уникальные значения, например - id

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeGallery.jsx
>      // Dispatch the fetchRecipes thunk to trigger the API call
комментарии лучше писать на русском, так как у нас русскоязычное приложение

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeGallery.module.scss
> +h2, p{
не задаем стили напрямую тегам, задаем через классы

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeGallery.module.scss
> +.catalogTitle{
можно ограничиться названием "title", так как мы используем модули

2023-11-17 14:30 UTC, lipnitskaite commented on front/src/components/Toast/ToastNotifications.jsx
> +import styles from './toastNotifications.module.scss';
названия файлов стилей с большой буквы везде, чтобы было единообразно

2023-11-17 17:37 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      alt="блюдо"
В закрмментированной строке я как раз предполагаю, что в alt пойдет название рецепта

2023-11-17 17:38 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeGallery.jsx
>      // Dispatch the fetchRecipes thunk to trigger the API call
Спрошу у Тимура, как это грамотно перевести, так как это его коммент

2023-11-18 08:58 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      // src="{recipe.image}"
удалено

2023-11-18 08:58 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      // alt="{recipe.name}"
удалено

2023-11-18 08:59 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      {/* <h3 className={styles.cardName}>{recipe.name}</h3> */}
удалено

2023-11-18 08:59 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      alt="блюдо"
закомментированный код удален

2023-11-18 09:01 UTC, MZ-87 commented on front/src/components/PageTitle/PageTitle.jsx
> +import styles from './pageTitle.module.scss';
исправлено

2023-11-18 09:02 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +        {/* <p className={styles.cardDescription__text}>{recipe.cookhours} час {recipe.cookminutes} мин.</p> */}
удалено

2023-11-18 09:08 UTC, MZ-87 commented on front/src/components/Toast/ToastNotifications.jsx
> +import styles from './toastNotifications.module.scss';
исправлено

2023-11-18 09:10 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.module.scss
> +h3,
Исправлено

2023-11-18 09:20 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeGallery.jsx
> +                /* eslint-disable-next-line react/no-array-index-key */
исправлено

2023-11-18 09:22 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeGallery.module.scss
> +h2, p{
исправлено

2023-11-18 09:27 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeGallery.module.scss
> +.catalogTitle{
исправлено

2023-11-18 09:27 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeGallery.jsx
>      // Dispatch the fetchRecipes thunk to trigger the API call
удалено

2023-11-18 09:31 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +      <div className={styles.cardDescription__item}>
cardWrapper и cardDescriptionWrapper переименованы в card и cardDescription соответственно

2023-11-18 09:46 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
> +        {/* здесь должен быть скрипт, добавляющий нужное количество звезд */}
создан ишью и прикреплена ссылка

2023-11-18 10:20 UTC, MZ-87 commented on front/src/components/RecipeGallery/RecipeGallery.jsx
> +      <div>
Пока да, когда на главной будут другие компоненты, кроме галереи, эту обертку можно будет убрать

2023-11-20 12:59 UTC, lipnitskaite approved these changes

2023-11-20 13:00 UTC, merged