Frontend #118 Сверстать компоненты подбора рецепта
Prostoe-menu/prostoemenu_dev pull request #128
Opened 2023-11-22 10:01 UTC by Grimlerih

Данные только сохраняются в этом же компоненте в useState. Потом логику поиска нужно будет подкрутить и выгружать в store при необходимости. Я там еще некоторые компоненты обновлял связанные с компонентом поиска ингредиентов.

2023-11-24 12:28 UTC, lipnitskaite requested changes
Очень хорошая работа проделана, спасибо!

Несколько моментов:
1. Фактическая верстка отличается от макета
2. При работе с гитом сверяйся, пожалуйста, с требованиями в [документации](https://github.com/Prostoe-menu/prostoemenu_dev/blob/frontend/front/README.md#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-git). Необходимо переименовать ветку и название ПР, также следить за тем, чтобы имена коммитов соответствовали доке.
3. Смерджь, пожалуйста, ветку frontend и поправь конфликты перед следующим ревью. После мерджа не забудь установить все зависимости npm i
4. После мерджа запусти npm run format, чтобы поправить форматирование в своих компонентах
5. Также при разработке можешь сразу ориентироваться на [стайлгайд](https://github.com/Prostoe-menu/prostoemenu_dev/pull/129)

2023-11-24 12:28 UTC, lipnitskaite commented on front/src/components/UI/Input/Input.jsx
> +  const registrationOptions = register
```suggestion
  const registerProperties
```

2023-11-24 12:28 UTC, lipnitskaite commented on front/src/components/RecipeSelection/RecipeSelection.jsx
> +  return (
Верстка не соответствует макету (контейнер должен быть отцентрован, в инпуте отсутствует лупа, кнопка "подобрать рецепт" находится ниже уровня инпута):

<img width="1789" alt="image" src="https://github.com/Prostoe-menu/prostoemenu_dev/assets/88855419/6a450e37-a5d4-4b6a-aea9-9b1579e29dee">

2023-11-24 12:28 UTC, lipnitskaite commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +  return (
верстка не соответствует макету: у чипсов есть нежелательный отступ, шрифт кнопки "очистить все" отличается от макета 

также стоит в будущем доработать логику, что при выборе ингредиента инпут очищается, но можно сделать в рамках следующего ПР, тк этот направлен преимущественно на верстку 

<img width="1358" alt="image" src="https://github.com/Prostoe-menu/prostoemenu_dev/assets/88855419/03c6e129-7f1a-4676-934c-e11a29d075d0">


также при добавлении ингредиентов марджин контейнера должен сокращаться - чем больше ингредиентов, тем меньше расстояние до каталога. сейчас у нас оно статичное:
макет:
<img width="1053" alt="image" src="https://github.com/Prostoe-menu/prostoemenu_dev/assets/88855419/783b47aa-9c59-4168-a3a3-9f8dc559b590">

реализация:
<img width="1423" alt="image" src="https://github.com/Prostoe-menu/prostoemenu_dev/assets/88855419/122f78f6-125e-4670-a040-bd1632c7b58e">

2023-11-24 15:19 UTC, Grimlerih commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +  return (
Тут по макету, статичный отступ в 60px
![Скриншот 24-11-2023 211857](https://github.com/Prostoe-menu/prostoemenu_dev/assets/61974670/b3e57dcf-f84e-4b01-a959-7eb4e4f22bc3)
![Скриншот 24-11-2023 211843](https://github.com/Prostoe-menu/prostoemenu_dev/assets/61974670/600c740c-0c72-4ac6-bfa3-52eb0d86c073)

2023-11-27 14:52 UTC, lipnitskaite requested changes
Выглядит все очень круто! 🙌 

У меня осталась только пара вопросов:

1. Ключевое: поправь, пожалуйста, импорты и проверь, на что ругается линтер
2. Необходимо переименовать ветку и название ПР, как требуется в документации.
3. Сейчас после третьего ряда ингредиентов тоже сохраняется марджин в 60пкс - это намеренно или случайно? Мне в целом нравится, как выглядит сейчас, можем обсудить корректировку макета с дизайнером

Остальные комменты опциональны и на твое усмотрение

2023-11-27 14:52 UTC, lipnitskaite commented on front/src/components/RecipeSelection/RecipeSelection.jsx
> +import style from './RecipeSelection.module.scss';
```suggestion
import styles from './RecipeSelection.module.scss';
```

[Стайлгайд](https://github.com/Prostoe-menu/prostoemenu_dev/blob/frontend/front/src/docs/style-guide.md#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2)

2023-11-27 14:52 UTC, lipnitskaite commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +import style from './SelectedRecipeList.module.scss';
```suggestion
import styles from './SelectedRecipeList.module.scss';
```

2023-11-27 14:52 UTC, lipnitskaite commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +        {/* eslint-disable-next-line */}
на что ругается линтер? можно ли пофиксить, а не дизейблить?

2023-11-27 14:52 UTC, lipnitskaite commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +          <p>Очистить всё</p>
можно ли дополнить компонент CloseButton, как я писала в первой итерации ревью?

2023-11-27 14:52 UTC, lipnitskaite commented on front/src/components/UI/Input/Input.module.scss
> +    background: url('../../../images/header_search.svg') center right 16px
здесь тоже стоит заменить относительные пути на абсолютные

2023-11-27 14:52 UTC, lipnitskaite commented on front/src/components/UI/Input/Input.jsx
> +    : {};
тоже можно сделать немного читабельнее:

```
const registerProperties = register && {
  required: {},
  pattern: {},
  min: {},
};
```

2023-11-27 14:52 UTC, lipnitskaite commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +import CloseButton from '../UI/CloseButton/CloseButton';
заменить относительные пути на абсолютные

2023-11-29 20:09 UTC, azozulya commented on front/src/components/UI/Input/Input.module.scss
> +    background: url('../../../images/header_search.svg') center right 16px
```
&_type_home {
    width: 1033px;
```
ширину поставить надо 100%. Инпут подстраивается под внешний блок, а то скрол горизонтальный вылез

2023-11-29 20:15 UTC, azozulya approved these changes
1. Может быть надо было назвать компонент, например, SearchByIngredients. Наверняка еще будет поиск просто по названию рецепта.
2. И IngredientsList понятнее SelectedRecipeList. 
3. В выпадашке надо поставить overflow-y: auto
4. Когда выбираешь из выпадашки ингредиент, поле поиска не очищается. Приходится стирать, чтобы написать что-то новое

2023-12-17 13:08 UTC, Grimlerih commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +        {/* eslint-disable-next-line */}
ругается на то что нельзя вешать слушатель на компонент div

2023-12-17 13:22 UTC, Grimlerih commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +          <p>Очистить всё</p>
там много пришлось бы изменять в коде решил так оставить, но ты там вроде сейчас переделала эту кнопку, нужно влить и уже изменять

2023-12-17 13:40 UTC, Grimlerih commented
> Выглядит все очень круто! 🙌
> 
> У меня осталась только пара вопросов:
> 
> 1. Ключевое: поправь, пожалуйста, импорты и проверь, на что ругается линтер
> 2. Необходимо переименовать ветку и название ПР, как требуется в документации.
> 3. Сейчас после третьего ряда ингредиентов тоже сохраняется марджин в 60пкс - это намеренно или случайно? Мне в целом нравится, как выглядит сейчас, можем обсудить корректировку макета с дизайнером
> 
> Остальные комменты опциональны и на твое усмотрение
1. Вроде исправил
2. Название ПР обновил, но не знаю как обновить название ветки, потому что для это нужно удалить текущую и залить новую. А ну нас тут ПР открыт на этой ветке.
3. Я писал тебе в tg по этому вопросу и я подумал что оставляем фиксированно 60px

2023-12-17 14:08 UTC, Grimlerih commented
> 1. Может быть надо было назвать компонент, например, SearchByIngredients. Наверняка еще будет поиск просто по названию рецепта.
> 2. И IngredientsList понятнее SelectedRecipeList.
> 3. В выпадашке надо поставить overflow-y: auto
> 4. Когда выбираешь из выпадашки ингредиент, поле поиска не очищается. Приходится стирать, чтобы написать что-то новое

1. SearchByIngredients, у меня же только контейнер реализован, компонент поиска уже был готовый, я же его просто применил.
2. IngredientsList мне кажется более обобщенное название, у нас же список выбранных элементов
3. Там по дизайну вроде скролла у чипсов нету, или я не так понял
4. Есть

2023-12-19 15:09 UTC, lipnitskaite commented on front/src/components/SelectedRecipeList/SelectedRecipeList.module.scss
> +  background-color: #e9f9e2;
тоже отрефакторить стили с использованием переменных

2023-12-19 15:09 UTC, lipnitskaite commented on front/src/components/UI/Button/Button.module.scss
> +  background: url('../../../assets/images/close_btn.svg');
нет, это здесь не нужно, мы используем абсолютные пути, а не относительные

еще заметила свой косяк, не обнулила паддинг у Button. добавь, пожалуйста для `.button` `padding: 0;`

2023-12-19 15:09 UTC, lipnitskaite commented on front/src/pages/HomePage.jsx
> +import React from 'react';
```suggestion
```

2023-12-19 15:18 UTC, lipnitskaite commented on front/src/components/SelectedRecipeList/SelectedRecipeList.jsx
> +import { v4 as uuidV4 } from 'uuid';
кстати соглашусь с Аней, что название компонента лучше поменять
например `SelectedIngredients`
List в названии тоже не нужно, потому что SelectedIngredients и так подразумевает, что это какой-то список

2023-12-19 15:18 UTC, lipnitskaite commented on front/src/components/RecipeSelection/RecipeSelection.jsx
> +import React, { useState } from 'react';
И здесь тоже бы название поменяла на например `RecipeSearch` , так как мы ищем рецепт, а не выбираем

2023-12-19 15:29 UTC, lipnitskaite commented on front/src/components/SelectedRecipeList/SelectedRecipeList.module.scss
> +.remove_btn {
кстати еще заметила: проверь, что ховер соответствует [макету](https://www.figma.com/file/hJUN2hrhTRCc5OxAe5NjE1/%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B5-%D0%9C%D0%B5%D0%BD%D1%8E-v1.1-MVP?type=design&node-id=889%3A3052&mode=design&t=gX0q4zoFV8hCdEkm-1)

2023-12-19 17:03 UTC, Grimlerih commented on front/src/components/UI/Button/Button.module.scss
> +  background: url('../../../assets/images/close_btn.svg');
а да, забыл убрать, там крч как то странно работает, тип если использовать алисы не удается провалиться в файл при нажатии мышкой, проверял и забыл убрать )

2023-12-21 22:02 UTC, lipnitskaite approved these changes

2023-12-21 22:03 UTC, merged