FRONTEND - #125 - Development - StarRating
Prostoe-menu/prostoemenu_dev pull request #139
Opened 2023-11-28 07:38 UTC by azozulya

[Issue 125](https://github.com/Prostoe-menu/prostoemenu_dev/issues/125)

1. Создала компонент UI/StarRating.
2. Количество звезд вынесла в константы STARS_TOTAL = 3, можно менять, если возникнет необходимость
3. Добавила [vite-plugin-svgr](https://github.com/pd4d10/vite-plugin-svgr#readme) Теперь Svg можно импортировать как компоненты

P.S. Пока svgr не работает, звезды выводятся как img и визуально не совсем одинаковые. Поправится с [Issue 132] после удаления arbnb (https://github.com/Prostoe-menu/prostoemenu_dev/issues/132)

![image](https://github.com/Prostoe-menu/prostoemenu_dev/assets/1482886/eed60656-c894-4ca6-9ddb-c3db8f1905c0)

2023-11-30 16:33 UTC, PopovDS617 commented on front/src/components/UI/StarRating/index.jsx
> +export default StarRating;
лучше сразу экспортировать из индекс файла, иначе это двойная работа
 
```suggestion
export {StarRating} from './StarRating'
```

2023-11-30 20:55 UTC, azozulya commented on front/src/components/UI/StarRating/index.jsx
> +export default StarRating;
Здесь это не работает) Я так писала, была ошибка. Надо удалить arbnb плагин. Я поправлю потом

2023-11-30 20:58 UTC, azozulya commented on front/src/components/UI/StarRating/StarRating.jsx
> +      // />
Это актуальная версия, когда заработает импорт svg как компонентов я это раскомментирую. Пока это не работает. В описании разъяснения

2023-12-01 22:58 UTC, lipnitskaite requested changes
все супер, спасибо!

единственный критичный момент в [StarRating.jsx](https://github.com/Prostoe-menu/prostoemenu_dev/pull/139/files#diff-f300a45c88ae016f60f8edece1fef3ca10bd92d2b2685a6439740347be29f02a) - не стоит оставлять подвешенный закомментированный код - лучше либо описать причину в документации компонента (с созданным issue), либо мерджить после того, как можно будет раскомментировать код и все будет работать корректно

остальные комменты - мои предложения, на твое усмотрение

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
>        <div className={styles.cardDescription__item}>
немного тяжело даются для восприятия два `div` `cardDescription__item`, думаю, можно поиграться с кодом, чтобы это сделать попроще, например, объединить их в один, и `timerImage` сделать не `div`, а `p` с `background`
приблизительно:

```
<div className={styles.cardDescription__item}>
        <StarRating label="Сложность" amount={2} />
        <div className={styles.timerImage} /> 1 час 30 мин.
 </div>
```

наименования классов я бы тоже скорректировала, либо в module.scss их делать nested

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.module.scss
> +.cardDescription__item {
если оставляем такое наименование, то нужно сделать nested к cardDescription

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeGallery.jsx
>          {recipes.length ? (
здесь я бы тоже убрала тернарный оператор и сделала через `recipes.length > 0 && <section>...</section>`
тк это проще воспринимается, чем условие

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeGallery.jsx
>  import RecipeCard from './RecipeCard/RecipeCard';
может, это тоже заменить на абсолютные пути?

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/RecipeGallery/RecipeGallery.jsx
> +                key={uuidV4()}
поставь, пожалуйста, коммент на будущее: не забыть убрать uuid и брать id с бэка

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/UI/StarRating/StarRating.jsx
> +      // />
в таком случае предлагаю либо написать это в документации в начале компонента, либо не мерджить этот ПР до тех пор, пока эта версия не станет рабочей

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/UI/StarRating/StarRating.jsx
> +import StarActiveSVG from 'images/star-filled.svg';
можно ли этого все-таки добиться стилями и fill, а не двумя разными svg? или это временное решение, пока StarSVG не работает?

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/UI/StarRating/StarRating.jsx
> +      //   key={uuidV4()}
а зачем здесь key?

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/UI/StarRating/StarRating.jsx
> +      //   className={cn({ [styles.active]: id + 1 <= amount })}
сложная для восприятия логика в className - мне, как человеку, который не погружен в код, не очень понятно, что происходит

2023-12-01 22:58 UTC, lipnitskaite commented on front/src/components/UI/StarRating/index.jsx
> +export default StarRating;
если мы начинаем работать с индекс-файлами для экспортов, то нужно обсудить с командой и создать issue, чтобы все компоненты привести к единому виду

2023-12-01 22:58 UTC, lipnitskaite commented on front/vite.config.js
> +
```suggestion
```

2023-12-03 16:18 UTC, azozulya commented on front/src/components/UI/StarRating/StarRating.jsx
> +import StarActiveSVG from 'images/star-filled.svg';
временное, будет одна картинка

2023-12-03 16:24 UTC, azozulya commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.jsx
>        <div className={styles.cardDescription__item}>
Сделаю в [issue 141](https://github.com/Prostoe-menu/prostoemenu_dev/issues/141)

2023-12-03 20:32 UTC, azozulya commented on front/src/components/UI/StarRating/StarRating.jsx
> +      // />
Можно подождать.

2023-12-03 20:34 UTC, azozulya commented on front/src/components/RecipeGallery/RecipeCard/RecipeCard.module.scss
> +.cardDescription__item {
Этот и все комменты ниже учту в [issue 141](https://github.com/Prostoe-menu/prostoemenu_dev/issues/141)

2023-12-04 20:24 UTC, lipnitskaite commented on front/src/components/UI/StarRating/StarRating.jsx
> +      // />
тогда предлагаю доработать этот ПР после того, как закончишь тот ПР с карточками, тк здесь уже будут какие-то комменты не актуальны

2023-12-05 20:21 UTC, azozulya commented on front/vite.config.js
> +
поправила

2023-12-05 20:24 UTC, azozulya commented on front/src/components/UI/StarRating/StarRating.jsx
> +      //   className={cn({ [styles.active]: id + 1 <= amount })}
Немного изменила, надеюсь так понятнее будет) Определяем сколько звезд закрашиваем, idx - номер звезды, 
`className={cn({ [styles.active]: rating > idx })}`

2023-12-08 14:11 UTC, lipnitskaite requested changes
все ок, только коммент по стилям у звездочек - думаю, лучше поправить в этом ПР, тк он касается непосредственно их

2023-12-08 14:11 UTC, lipnitskaite commented on front/src/components/UI/StarRating/StarRating.jsx
> +  const stars = [...Array(STARS_TOTAL)].map((_, idx) => {
сейчас на превью карточки звездочки активны, то есть как будто можно видоизменить сложность рецепта, а так быть не должно - они должны нести только информативную функцию

2023-12-09 17:55 UTC, azozulya commented on front/src/components/UI/StarRating/StarRating.jsx
> +import cn from 'classnames';
поправила

2023-12-09 17:56 UTC, azozulya commented on front/src/components/UI/StarRating/StarRating.jsx
> +  const stars = [...Array(STARS_TOTAL)].map((_, idx) => {
Не заметила, ховер от тултипа перекрывал звездочки. Неожиданно. Поправила

2023-12-10 14:56 UTC, lipnitskaite approved these changes

2023-12-10 14:56 UTC, merged