FRONTEND-#141-Refactor-Recipe-card
Prostoe-menu/prostoemenu_dev pull request #143
Opened 2023-12-03 20:50 UTC by azozulya

[Issue 141](https://github.com/Prostoe-menu/prostoemenu_dev/issues/141)

1. Вынесла всю логику из RecipeList на страницу HomePage. Теперь RecipeList рисует список рецептов. Можно использоать и для поиска и для блока "Вам может понравиться"
2. Добавила лайаут для сайта.

2023-12-04 20:22 UTC, lipnitskaite requested changes
Проделана огромная и очень классная работа!
Особенно мне понравилось твое предложение с Layout и Outlet, спасибо!

Основной момент, который нужно доработать - получаемые данные в карточке:
макет:
<img width="678" alt="image" src="https://github.com/Prostoe-menu/prostoemenu_dev/assets/88855419/84b712d9-eb09-488b-af95-a643cbb056c3">

сейчас:
<img width="658" alt="image" src="https://github.com/Prostoe-menu/prostoemenu_dev/assets/88855419/ebc5f752-cd9a-4c3f-a4e9-9a29dbc5ed3a">

что я предлагаю:
1. проверить, какие данные возвращает бэк по эндпойнту /recipes - что всех данных достаточно для корректного отображения компонента. например, сейчас вместо изображения текст, а не url, также нет id, который нам пригодится, а еще главного изображения рецепта для обложки, попросить команду это добавить (в коде описала подробнее)
2. сделать дефолтное изображение на случай, если пользователь не загрузил свои фото
3. доработать продолжительность готовки
4. проверить стили - в макете тень как будто сильнее, чем по факту
5. и небольшие рекомендации по улучшению: поправить fetchRecipes, сразу добавить лоадер, который Вера добавила в макет, чтобы убрать временную текстовую заглушку и пр

2023-12-04 20:29 UTC, lipnitskaite commented on front/src/pages/HomePage.jsx
> +        Пожалуйста, подождите, выполняется загрузка...
если удобнее отдельным пр - давай отдельным, нужно будет только issue создать

2023-12-12 09:56 UTC, azozulya commented on front/src/components/Layout/Layout.jsx
> +import Footer from './Footer/Footer';
Поправила

2023-12-12 09:56 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.jsx
> +import React from 'react';
fix

2023-12-12 09:57 UTC, azozulya commented on front/src/components/RecipeList/RecipeList.jsx
> +          <RecipeCard recipe={recipe} key={uuidV4()} /> // заменить на recipe.id
Заменила

2023-12-12 09:59 UTC, azozulya commented on front/src/vendor/global.scss
> +.loading {
Добавила Loader в UIKit и стили туда же перенесла

2023-12-12 10:00 UTC, azozulya commented on front/src/pages/HomePage.jsx
> +        Пожалуйста, подождите, выполняется загрузка...
Добавила Loader

2023-12-12 10:00 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.jsx
> +        <p className={styles.cookingTime}>{cookingTime}</p>
готово

2023-12-12 10:01 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +
fix

2023-12-12 10:01 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +.recipe {
поправила

2023-12-12 10:01 UTC, azozulya commented on front/src/components/Layout/Layout.jsx
> +import React from 'react';
поправила

2023-12-17 21:06 UTC, azozulya commented on front/src/components/RecipeList/RecipeList.jsx
> +      <section className={styles.recipeList}>
Добавила список

2023-12-17 21:08 UTC, azozulya commented on front/src/components/RecipeList/RecipeList.jsx
> +  <>
А зачем здесь section? Я не стала добавлять, чтобы лишних тегов не было. В main будет заголовок и <ul> с рецептами

2023-12-17 21:09 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.jsx
> +    <div className={styles.recipe}>
поправила

2023-12-27 21:08 UTC, azozulya commented on front/src/pages/HomePage.jsx
> +import fetchRecipes from 'store/slices/recipe/recipeThunk';
Текст ошибки вынесла в константы и сам текст изменила на 'Упс! Что-то пошло не так при загрузке рецептов, но мы уже работаем над этим!'

2024-01-22 21:58 UTC, lipnitskaite approved these changes
все супер! мои комменты опциональны и по желанию (кроме тех, которые связаны с расхождениями в макете, они обязательны)
очень хорошая работа проделана, спасибо!

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/Layout/Layout.module.scss
> +  padding-top: 150px;
думаю, тут имеет смысл тогда объединить `padding: 150px 72px 0 72px;`

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +  @media only screen and (min-width: 768px) {
может, вынести все media-queries в конец файла, как обычно делаем?

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +  &:hover {
по макету разве есть какой-то транзишн на ховере изображения?

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +.defaultImg {
это временная реализация, верно? если так, я бы добавила поясняющий коммент в код

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +  margin: 0 0 10px 0;
по макету другой марджин

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +  @media only screen and (min-width: 768px) {
аналогично предыдущему комменту, предлагаю все media queries структурировать в конце файлов

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeList.jsx
> +  <>
отдельные логические куски кода на странице лучше разбивать на section для лучшей семантики/accessibility. подробнее можно прочитать [здесь](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)
сейчас у нас есть точно две отдельных логических секции на странице - форма поиска и контейнер карточек, и я бы предложила их лучше разделить на sections. если посмотреть страницу в dev-tools в браузере, это будет более заметно

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeList.jsx
> +        {recipes.map((recipe, idx) => (
id карточки не возвращается с бэка? если возвращается, то index лучше заменить на id

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeList.module.scss
> +  margin-top: 0;
margin у headings лучше полностью обнулять и задавать кастомный - сейчас он не соответствует макету

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/RecipeList/RecipeList.module.scss
> +  @media only screen and (min-width: 1231px) {
аналогично предыдущим комментам по media queries

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/UI/Loader/Loader.jsx
> +    <div className={styles.spinner}>
может, можно улучшить семантику? чтобы не было div-div-div

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/UI/Loader/Loader.module.scss
> +  background: rgb(63, 249, 220);
по идее следущий background перезаписывает этот, или нет?

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/components/UI/Loader/Loader.module.scss
> +  background-color: #fff;
можно переиспользовать цвета с переменных

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/helpers/utils.js
> +  if (minutes < 60) return `${minutes} мин.`;
как по макету, может быть у нас сокращение "мин." или должно быть "минут"?

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/pages/HomePage.jsx
> +      {isLoading && <Loader />}
очень понравилась в целом работа с лоадером, обработкой ошибой и как здесь все учла :)

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/store/slices/recipe/recipeThunk.js
>  // Replace 'your_api_endpoint' with the actual API endpoint
предлагаю комментарии убрать или переписать на русский

2024-01-22 21:58 UTC, lipnitskaite commented on front/src/store/slices/recipe/recipeService.js
> +const URL = `${import.meta.env.VITE_API_URL}${RECIPES_LIST_URL}`;
  нужно ли это выносить в константы, если у нас.и так этот слайс отвечает только за рецепты, и эта урл им посвящена?

2024-01-26 07:20 UTC, azozulya commented on front/src/components/Layout/Layout.jsx
> +import React from 'react';
Теперь точно поправила

2024-01-26 07:24 UTC, azozulya commented on front/src/components/RecipeList/RecipeList.jsx
> +  <>
Да, ты права, добавила

2024-01-26 07:25 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.jsx
> +  const imgUrl = photos[0]?.photo;
Это я поправила, бэк отдает сейчас cover_path

2024-01-26 07:28 UTC, azozulya commented on front/src/components/Layout/Layout.module.scss
> +  padding-top: 150px;
Импорт удалила, теперь точно) Падинг поправила

2024-01-26 07:33 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +  @media only screen and (min-width: 768px) {
Для меня плюс в том, что если меняется название класса или он вообще удаляется, то не надо искать блоки в медиа(которое внизу файла), которые к нему относятся. Сейчас у нас маленькие файлы стилей, но если они разрастутся, то данный подход будет очень удобен. И потом в итоговом файле при сборке все медиа будут в конце все-равно

2024-01-26 07:51 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +  &:hover {
Удалила. Не уверена, что я его добавила)

2024-01-26 07:51 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +.defaultImg {
Добавила коммент

2024-01-26 07:51 UTC, azozulya commented on front/src/components/RecipeList/RecipeCard/RecipeCard.module.scss
> +  margin: 0 0 10px 0;
поправила

2024-01-26 07:53 UTC, azozulya commented on front/src/components/RecipeList/RecipeList.jsx
> +        {recipes.map((recipe, idx) => (
Прописан id рецепта, но поскольку рецепт один и он просто множится, то я добавила еще индекс, иначе ошибка об одинаковом ключе`key={`${recipe.id}-${idx}`}`

2024-01-26 08:00 UTC, azozulya commented on front/src/components/RecipeList/RecipeList.module.scss
> +  margin-top: 0;
поправила
![Screenshot 2024-01-26 095759](https://github.com/Prostoe-menu/prostoemenu_dev/assets/1482886/6a1ba418-300f-4d47-a9a2-abdbdf470c67)

2024-01-26 08:29 UTC, azozulya commented on front/src/components/UI/Loader/Loader.jsx
> +    <div className={styles.spinner}>
Добавила ариа аттрибуты. 

`<div
      className={styles.spinner}
      aria-busy={'true'}
      aria-describedby="Loading..."
    >`

2024-01-26 08:29 UTC, azozulya commented on front/src/components/UI/Loader/Loader.module.scss
> +  background: rgb(63, 249, 220);
Да, перезаписывает. Убрала.

2024-01-26 08:30 UTC, azozulya commented on front/src/components/UI/Loader/Loader.module.scss
> +  background-color: #fff;
Цвет поправила, вынесла бэкграунд в цвета тоже

2024-01-26 08:35 UTC, azozulya commented on front/src/store/slices/recipe/recipeService.js
> +const URL = `${import.meta.env.VITE_API_URL}${RECIPES_LIST_URL}`;
Мне кажется удобно, когда все ручки/урлы будут прописаны в одном месте.

2024-01-26 08:37 UTC, azozulya commented on front/src/store/slices/recipe/recipeThunk.js
>  // Replace 'your_api_endpoint' with the actual API endpoint
Удалила, там итак все понятно

2024-01-26 09:11 UTC, azozulya commented on front/src/helpers/utils.js
> +  if (minutes < 60) return `${minutes} мин.`;
Добавила минуты

2024-01-28 19:51 UTC, lipnitskaite approved these changes

2024-01-28 19:51 UTC, merged