FRONTEND-#131-ScrollUpButton
Prostoe-menu/prostoemenu_dev pull request #154
Opened 2024-01-18 21:18 UTC by azozulya

1. Добавила кнопку "Наверх" на главную. 
2. Поправила стили для кнопок с view="tertiary" в ButtonUI
![image](https://github.com/Prostoe-menu/prostoemenu_dev/assets/1482886/6d6d7dc1-c428-4f1f-8822-0a620b128f1d)

2024-01-24 19:38 UTC, lipnitskaite requested changes
Очень хорошая работа, спасибо! Работает все очень приятно и плавно :)

Пришлось вернуть из-за баги: Если много карточек, и скроллишь вверх, то кнопка тоже поднимается и расположена поверх карточек
<img width="1791" alt="image" src="https://github.com/Prostoe-menu/prostoemenu_dev/assets/88855419/f5a81d3a-394f-4df4-9add-07689915d118">

Остальные комменты опциональны и на усмотрение (кроме компонента UI/Button, если его меняем, нужно проверить, не ломаются ли другие кнопки (напр, на стр добавления рецепта)

2024-01-24 19:38 UTC, lipnitskaite commented on front/src/components/UI/Button/Button.jsx
> +  iconPosition = 'right',
а есть ли принципиальная разница? то же самое ведь, только под другим соусом, а остальные кнопки тоже придется править

2024-01-24 19:38 UTC, lipnitskaite commented on front/src/components/UI/ScrollUpButton/ScrollUpButton.jsx
> +import { useCallback, useEffect, useState } from 'react';
импорты внешних библиотек идут в самом начале

2024-01-26 11:07 UTC, azozulya commented on front/src/components/UI/Button/Button.jsx
> +  iconPosition = 'right',
Я не нашла кнопок с иконками. Изменила, потому что стили записаны наоборот. Раньше по умолчанию иконка была слева, а выводилась справа.

2024-01-26 11:09 UTC, azozulya commented on front/src/components/UI/ScrollUpButton/ScrollUpButton.jsx
> +import { useCallback, useEffect, useState } from 'react';
Линтер хочет так) Если меняю местами, ошибку выводит и просит поменять

2024-01-26 11:11 UTC, azozulya commented on front/src/components/UI/ScrollUpButton/ScrollUpButton.jsx
> +    if (window.scrollY > 700) {
Можно, заменила

2024-01-26 11:12 UTC, azozulya commented on front/src/components/UI/ScrollUpButton/ScrollUpButton.jsx
> +    <>
+

2024-01-26 11:17 UTC, azozulya commented
> Очень хорошая работа, спасибо! Работает все очень приятно и плавно :)
> 
> Пришлось вернуть из-за баги: Если много карточек, и скроллишь вверх, то кнопка тоже поднимается и расположена поверх карточек <img alt="image" width="1791" src="https://private-user-images.githubusercontent.com/88855419/299433297-f5a81d3a-394f-4df4-9add-07689915d118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjY0NTcsIm5iZiI6MTcwNjI2NjE1NywicGF0aCI6Ii84ODg1NTQxOS8yOTk0MzMyOTctZjVhODFkM2EtMzk0Zi00ZGY0LTlhZGQtMDc2ODk5MTVkMTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEwNDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NTk5YmE4YTY5NWZkM2UxNzZlZjM5NGJmMGUxN2NlYzY5ZmNiNDYxMGEzNjE4YTM5YTM2MWFmOTAzMTUwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zoohPwwZZDsKCZjuFAPpLP6Ck73EudBvDcTEDxn_g7s">
> 
> Остальные комменты опциональны и на усмотрение (кроме компонента UI/Button, если его меняем, нужно проверить, не ломаются ли другие кнопки (напр, на стр добавления рецепта)

Мне не показалось, что это проблема. Она должна быть в правом нижнем углу, текст прочитать можно. Как вариант просто стрелку оставить

2024-01-28 20:00 UTC, lipnitskaite approved these changes
к коду комментариев нет, поэтому аппрув

насчет кнопки: мне кажется, что это не очень хороший user experience, если кнопка загораживает текст карточек, как это реализовано сейчас. если мы хотим, чтобы она была сохранялась при скролле, то ее нужно сдвинуть так, чтобы она не перекрывала контент рецептов (как вариант, можно сделать просто стрелочкой, как ты предложила). это мое мнение, поэтому я бы тебе посоветовала обсудить это с Катей, если ей это ок, то можешь сразу схлопнуть коммиты и смерджить.

2024-04-05 13:11 UTC, merged