BACKEND - #211 - Common - create class AcceptedSymbolsValidator
Prostoe-menu/prostoemenu_dev pull request #213
Opened 2024-06-25 13:32 UTC by asbabushkin

Функция проверки входящих текстовых данных validate_accepted_symbols() заменена на класс AcceptedSymbolsValidator для единообразия валидаторов.

Isort теперь сортирует импорты по-новому, поэтому много формальных изменений.

2024-07-09 20:41 UTC, 4uku requested changes
конфиг для исорта был не совсем верным. импорты должны быть расположены в следующем порядке: сначала встроннные пакеты, затем установленные пакеты, затем свои модули. исправил конфиг, надо заново отсортировать

2024-07-09 20:41 UTC, 4uku commented on back/ingredients/migrations/0003_category_alter_ingredient_sort_and_more.py
> +def validate_accepted_symbols(value):
чтобы уж таких костылей не было, можно грохнуть все миграции, кроме первой, и заново их сгенерить. у нас на проде ничего нет, на тесте тоже неактуальное все, мы с тобой единственные, кто работает над проектом, так что ничего мы не потеряем. в принципе, до первого релиза на проде за консистентность миграций вообще можно не переживать

2024-07-09 20:41 UTC, 4uku commented on back/common/validators.py
> +        self.accepted_symbols = set(accepted_symbols)
снова решил каждый раз делать кортеж из строки?

2024-07-10 12:51 UTC, asbabushkin commented on back/common/validators.py
> +        self.accepted_symbols = set(accepted_symbols)
Это потому что блэк вдруг решил в конструкции ACCEPTED_SYMBOLS = set(
    "абвгдеёжзийклмнопрст...") каждую букву отдельной строкой прописать. Получился столбец шириной в одну букву и высотой под сотню символов, выглядело ужасно даже для сетингсов.
    Сейчас вернул все к множеству, как было, вроде не переделывает.

2024-07-10 12:56 UTC, asbabushkin commented on back/ingredients/management/commands/load_ingr.py
> +        with open("back/data/ingredients.json", "rb") as ingredients:
понятно, исправил

2024-07-10 13:09 UTC, 4uku commented on back/common/validators.py
> +        self.accepted_symbols = set(accepted_symbols)
> Это потому что блэк вдруг решил в конструкции ACCEPTED_SYMBOLS = set( "абвгдеёжзийклмнопрст...") каждую букву отдельной строкой прописать. Получился столбец шириной в одну букву и высотой под сотню символов, выглядело ужасно даже для сетингсов. Сейчас вернул все к множеству, как было, вроде не переделывает.

в этом случае, можно указать блэку игнорировать строку, с которой у него сложности. либо еще можно попробовать так:
`ACCEPTED_SYMBOLS = set(
    "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ\
    abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\
    0123456789!№;%:?*()/.,\«»—–- \"'°+¼½"
)`

2024-07-10 13:12 UTC, 4uku commented
> > конфиг для исорта был не совсем верным. импорты должны быть расположены в следующем порядке: сначала встроннные пакеты, затем установленные пакеты, затем свои модули. исправил конфиг, надо заново отсортировать
> 
> Не помогло, все равно просто по алфавиту импорты сортирует. Почему вообще слетели настройки, мы же ничего не меняли?

подозреваю, что проблема твоя локальная, потому что у меня при выполнении `isort .` в папке back получается такой результат:
![image](https://github.com/Prostoe-menu/prostoemenu_dev/assets/63356555/801469a3-f91b-446a-aba4-d34d79169b09)

2024-07-10 13:59 UTC, asbabushkin commented on back/ingredients/migrations/0003_category_alter_ingredient_sort_and_more.py
> +def validate_accepted_symbols(value):
миграции грохнул, перезалил.

2024-07-10 14:12 UTC, asbabushkin commented on back/common/validators.py
> +        self.accepted_symbols = set(accepted_symbols)
Ок. Возможно, я эти столбики не в сетингсах, а в миграциях видел, уже не уверен. Они и сейчас в новых миграциях вылезли, хотя блэк я не применял.

2024-07-10 14:41 UTC, 4uku commented on back/common/validators.py
> +        self.accepted_symbols = set(accepted_symbols)
> Ок. Возможно, я эти столбики не в сетингсах, а в миграциях видел, уже не уверен. Они и сейчас в новых миграциях вылезли, хотя блэк я не применял. Видимо, джанго так раскидывает.

в миграциях джанго сам подставляет значения из сеттингсов, потому что миграция - это история изменений модели на основе, в том числе, настроек, которые могут меняться постоянно

2024-07-10 14:43 UTC, 4uku commented
> > подозреваю, что проблема твоя локальная, потому что у меня при выполнении `isort .` в папке back получается такой результат (слева старая версия, справа - новая):
> 
> ок, буду искать у себя.

если ты используешь Pycharm, то укажи папку back как source root. в VScode это тоже как можно сделать. должно помочь

2024-07-11 13:36 UTC, asbabushkin commented
> если ты используешь Pycharm, то укажи папку back как source root. в VScode это тоже как можно сделать. должно помочь

Back отмечен source root'ом, не помогает. Выкрутился передавая папку в команду: isort back. Импорты отсортировал.

2024-07-14 11:33 UTC, 4uku approved these changes

2024-07-14 18:45 UTC, merged